### ISSUE TITLE
Tab completion for Slack emoji

### ISSUE THREAD

**Issue by LukeMoll** [bqv/weechat-slack#3]
Since there are no emoji rendering on Weechat's side (although plugins exist to remedy this), it would be useful to have tab completion when starting an emoji name like `:think` -> `:thinking-face:`. Even more useful (and unique to a Slack setup) would be completion to nonstandard emoji names, like aliases or custom emoji created through Slack.

**Comment by sim642** [comment]
Some emoji scripts (I think `emoji.lua` at least) for WeeChat supports tab completing partial emoji names like that already. It might not be needed to duplicate existing functionality just for that, only for custom ones possibly.

**Comment by bqv** [comment]
Excellent, thanks sim

**Comment by bqv** [comment]
Partially implemented in bqv/weechat-slack@cb59773. Custom emoji are all that remain.
