### ISSUE TITLE
Prioritise most recent senders when tab-completing nicks for reply

### ISSUE THREAD

**Issue by LukeMoll** [bqv/weechat-slack#4]
If there are two users `joel` and `joseph`, `jo` tab-completes to `joel`, as it is alphabetically closer. However, if `joseph` sent a message more recently than `joel`, then the user is more likely to be replying to `joseph` than `joel`, so `joseph` should be preferred for completion. (Perhaps this scope should be limited to the last _n_ messages or only those within _m_ pages of backlog)

**Comment by bqv** [comment]
Closing this as implemented in 58d46c71d5f03af8ae8789766530b12f305e0440, whose bug is tracked by #13 instead
